# SPDX-FileCopyrightText: 2022 Tezos Commons
# SPDX-License-Identifier: LicenseRef-MIT-TC

# To update hackage and stackage indexes used by CI run:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-18.10

packages:
- .

extra-deps:
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    146da727ff486c46b0ec9f392d955f07d797848e # master
  subdirs:
    - code/cleveland
    - code/lorentz
    - code/morley
    - code/morley-client
    - code/morley-prelude

- git:
    https://gitlab.com/morley-framework/indigo.git
  commit:
    e879e5f282afb8d25d72d8ba132f22d3d9e628a1 # master
  subdirs:
    - .

- git:
    https://gitlab.com/morley-framework/morley-ledgers.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    b39a971f42bb113a5b3e23c9145253e27ad6e049 # master
  subdirs:
    - code/morley-ledgers
    - code/morley-ledgers-test

- git:
    https://gitlab.com/morley-framework/morley-metadata.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    81b947ca1d74f3487a5b5c8e2141c37bf374f747 # master
  subdirs:
    - code/morley-metadata
    - code/morley-metadata-test

# Required by morley
- git: https://github.com/serokell/base-noprelude.git
  commit: 1282e0b992b00089d55228a2aa9edc4a3581c319
- hex-text-0.1.0.4
- show-type-0.1.1
- named-0.3.0.1
- co-log-0.4.0.1
- colourista-0.1.0.1
- ansi-terminal-0.10.3
- galois-field-1.0.2
- elliptic-curve-0.3.0
- pairing-1.1.0
- protolude-0.2.4
- poly-0.4.0.0
- groups-0.4.1.0
- crypto-sodium-0.0.5.0
- NaCl-0.0.5.0
- libsodium-1.0.18.2
- OddWord-1.0.2.0

# Required by indigo
- summoner-2.0.1.1
- generic-data-0.8.3.0
- neat-interpolation-0.3.2.6
- optparse-applicative-0.15.1.0
- megaparsec-8.0.0

# Stable parts of morley available from Hackage
- tasty-hunit-compat-0.2
