# SPDX-FileCopyrightText: 2022 Tezos Commons
# SPDX-License-Identifier: LicenseRef-MIT-TC

env:
  TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER: "Y"
  # this key is defined in local-chain bootstrap accounts list in
  # https://github.com/serokell/aquarius-infra/blob/master/servers/albali/chain.nix
  TASTY_CLEVELAND_MONEYBAG_SECRET_KEY: "unencrypted:edsk4JeHGnXM5nz2cyW9R5xTpM1Wk6ZgZF2j6k8h235akhSPbnEEnz"

steps:
  - label: hlint
    if: &not_scheduled_autodoc
      build.branch != "autodoc/master" && build.branch != "master" && build.source != "schedule"
    commands:
    - nix run -f ci.nix pkgs.hlint -c
        ./scripts/lint.sh

  - label: reuse lint
    if: *not_scheduled_autodoc
    commands:
    - nix run -f ci.nix pkgs.reuse -c
        reuse lint

  - label: check trailing whitespace
    if: *not_scheduled_autodoc
    commands:
    - .buildkite/check-trailing-whitespace.sh

  - label: xrefcheck
    if: *not_scheduled_autodoc
    commands:
    - nix run -f ci.nix xrefcheck -c xrefcheck
    retry:
      automatic:
        limit: 1

  - label: build
    if: *not_scheduled_autodoc
    key: build
    commands:
    - nix-build ci.nix -A all-components

  - label: test
    if: *not_scheduled_autodoc
    key: test
    depends_on: build
    commands:
    - nix-build ci.nix -A packages.homebase-lite.tests.homebase-lite-test
    - ./result/bin/homebase-lite-test --cleveland-mode=disable-network

  - label: test-local-chain-011
    if: *not_scheduled_autodoc
    env:
      TASTY_CLEVELAND_NODE_ENDPOINT: "http://localhost:8734"
    depends_on:
      - build
      - test
    commands: &network-test
    - nix-build ci.nix -A packages.homebase-lite.tests.homebase-lite-test
    - export TASTY_CLEVELAND_DATA_DIR="$(mktemp -d --tmpdir="$$PWD")"
    - nix run -f ci.nix tezos-client -c
      ./result/bin/homebase-lite-test --cleveland-mode=only-network

  - label: scheduled hangzhounet test
    if: build.source == "schedule"
    depends_on: build
    env:
      TASTY_CLEVELAND_NODE_ENDPOINT: "https://hangzhou.testnet.tezos.serokell.team"
    commands: *network-test
    retry:
      automatic:
        limit: 1
    timeout_in_minutes: 240

  - label: weeder
    if: *not_scheduled_autodoc
    depends_on: build
    commands:
    - nix-build ci.nix -A weeder-script
    - ./result

  - label: haddock
    if: *not_scheduled_autodoc
    depends_on: build
    commands:
    - nix-build ci.nix -A haddock --no-out-link
